### ISSUE TITLE
Compile File

### ISSUE THREAD

**Issue by rickbau5** [uidaho/squireproject#101]
Implement a way to compile a file. Limited only to Java. Compilation is going to be done in Docker containers. 

Logical extension of this issue
- ~~Execute a compilation~~ (Decided against execution 4/20)
- Report errors (highlighting in the editor, is this possible?)
- Compile to JAR

**Comment by rickbau5** [comment]
@backburn could you install a jdk onto the server for this please?

**Comment by brandonjank** [comment]
OpenJDK 7 and OpenJRE 7 installed and server setup documentation updated. :dancer:

**Comment by rickbau5** [comment]
added with #150
