### ISSUE TITLE
Project list messed up view

### ISSUE THREAD

**Issue by brec9824** [uidaho/squireproject#103]
The project list page displays projects in nonuniform size. Which can cause weird formatting like projects skipping lines. You can replicate this by zooming in or out in your browser.
![error1](https://cloud.githubusercontent.com/assets/16866862/14689640/13a2167a-06fd-11e6-9503-f652d28e551a.PNG)

**Comment by rickbau5** [comment]
I noticed this as well. Probably all should be forced to fill to an exact size.
