### ISSUE TITLE
Can't Reset Password

### ISSUE THREAD

**Issue by rickbau5** [uidaho/squireproject#106]
Get this error trying to reset password:
![image](https://cloud.githubusercontent.com/assets/11299264/14694025/86b1a7f4-0719-11e6-9170-8e611ed1abe9.png)

**Comment by rickbau5** [comment]
@brec9824 you set this up right? Any idea what this means?

**Comment by brec9824** [comment]
@rickbau5 I just tested it and it worked on mine. Do you have your .env file set like this: 
![capture](https://cloud.githubusercontent.com/assets/16866862/14694233/43d5c42c-071b-11e6-80fb-388bb924e9d6.PNG)

**Comment by rickbau5** [comment]
Thanks that was the issue! I remember that changing now, totally forgot to update mine though.
