### ISSUE TITLE
Bread Crumb

### ISSUE THREAD

**Issue by rickbau5** [uidaho/squireproject#108]
I like the breadcrumb in most situations, but there's some cases (such as below) that don't really work. Can we perhaps make a new layout that's a sublayout of `main_layout` with the bread crumb? and then pages where it's not necessary or doesn't fit, we can just use the regular main layout without it? Or is there a better way to do that

![image](https://cloud.githubusercontent.com/assets/11299264/14698043/3eaa611e-073f-11e6-9d66-d218aa2bc58c.png)

**Comment by rickbau5** [comment]
Or another thought is include it explicitly if you'd like it on that page, like the for files list

**Comment by brec9824** [comment]
In my pull request I made the breadcrumb optional. So we dont have to have it on every page.
