### ISSUE TITLE
Odd Link In Breadcumb

### ISSUE THREAD

**Issue by rickbau5** [uidaho/squireproject#110]
In the breadcrumb, clicking on `Editor` takes you back to the project finder.

**Comment by brandonjank** [comment]
This behavior was amended with 18dc6d9 and 750a56e. There is no default editor page, and the editor requires a project and file. If they were to click on the project name in the breadcrumb it would then go to the file listing so they could choose a file to edit. No parameters will be forwarded to project page so they can pick a project to see the file listing.
