### ISSUE TITLE
Sorting on Projects

### ISSUE THREAD

**Issue by rickbau5** [uidaho/squireproject#116]
Implement sorting functionality for project page

**Comment by brec9824** [comment]
@rickbau5 you might want to take a look at https://laravel.com/docs/5.2/pagination

**Comment by rickbau5** [comment]
@brec9824 what's the relevance of pagination for sorting?

**Comment by brec9824** [comment]
Whoops copied the wrong link. I will see if I kind find the page I meant to link.

**Comment by rickbau5** [comment]
@brec9824 
Damn. You. Just sent me down a 3 hour rabbit hole with pagination. It was a pain to get it to work WITH sorting. So when you went to page 2 it didn't sort page 2's content only, but show you page two of the entire sorted contents. The default pagination provided by `Project::paginate(16)` doesn't support sorting. [Had to do some trickery](https://github.com/uidaho/squireproject/commit/3866c99f1b7a87673debe3af742be0c86237318f#diff-3e1aa0f2a44d26e00cfc24819911a0e1R18) to get it to work.
