### ISSUE TITLE
Cant get to project files list

### ISSUE THREAD

**Issue by brec9824** [uidaho/squireproject#126]
I know before we could get to this page but now if you create the first file for a project the redirect gets a 404 error.

**Comment by rickbau5** [comment]
does the project title have a space in it? this is still handled differently in the editor than in the project provider stuff

**Comment by brec9824** [comment]
No it doesnt have any spaces. It looks like it should be working squireproject.com/editor/edit/This-is-a-title/ThisFile.txt but I get a 404 page.

**Comment by rickbau5** [comment]
sorry what I meant, is does the project title have spaces in it. Trying replacing `This-is-a-title` with `This%20is%20a%20title`in the url

**Comment by rickbau5** [comment]
What's happening is the editor controller or whatever is looking the project up by `This-is-a-title` so it 404's, its not converting the dashes to spaces before querying the database

**Comment by brec9824** [comment]
Ok, I am going to try and fix this because I want to list the join requests on the side of the files list page.

**Comment by brec9824** [comment]
Fixed this in my current branch

**Comment by brandonjank** [comment]
It was converting them before. It looks like someone reverted it

**Comment by brandonjank** [comment]
Additionally, project names should not have spaces to begin with, and if so
converted to dashes at creation. A la github et al

**Comment by rickbau5** [comment]
Idk I don't think projects titles shouldn't be allowed to have spaces in them. It seems sort of like an arbitrary limitation to me

**Comment by brandonjank** [comment]
It's limited that way on every site, similar to what were doing, that I
know of.

**Comment by rickbau5** [comment]
Kickstarter doesn't

**Comment by brandonjank** [comment]
Kickstarter uses hyphen replacement. HTML entities (%20) should never be in the URL.

**Comment by brandonjank** [comment]
This should be resolved with pull request #136

**Comment by brec9824** [comment]
Resolved with pull request #136
