### ISSUE TITLE
Need list of things done for sprint 7 group turn-in

### ISSUE THREAD

**Issue by brandonjank** [uidaho/squireproject#130]
THIS IS URGENT. Please put a list of tasks you have completed here or in c9. Otherwise ill have to make stuff up based on whats in git.

Ill place mine below as an example.

@uidaho/lambda @drspaceman0 @drop-table-lol  @mora5651 @rickbau5 @bolt1003 @brec9824

**Comment by brandonjank** [comment]
- The project was migrated to use bootstrap CSS, creating a clean and unified look for the project.
- Modified site to be a fully responsive layout. Users can use any modern browser on any device, including apple and android devices.
- Created a new view for the project list.
- Created a new view for project file listing that can be included as a widget on any page.
- Created a custom file, project, or user not found page.
- Active users, their current line position, and color coding has been fully implemented.
- Syntax coloring for Java has been implemented.
- Files can now be created and deleted by project members.
- Editor was integrated into the new bootstrap format.
- Created searchable and orderable project file listing.
- Created file location breadcrumb.
- File export functionality has been added. 
- Unit tests for all methods and user interface elements in the editor has been implemented.

**Comment by drop-table-lol** [comment]
Created Settings Controller
Created Settings Class
Created Settings Page
Created Settings Table
Eric and John (mars2681 and snev7821)

**Comment by rickbau5** [comment]
- Implemented full fledged project creation, as well as deletion
- Created unit testing for Login, Registration, General permissions, Project creation & viewing
- Implemented pagination for project list view
- Implemented sorting functionality for project list view, ascending/descending by author, title, and creation/modified dates.
- Updated create project, login, register, and reset forms to all use new css theme

**Comment by brec9824** [comment]
Added Comment section:
- User must be signed in to leave comment
- Error messages dealing with comments
- Edit past comments
- Delete past comments
- Success message

GitHub link: https://github.com/uidaho/squireproject/pull/91

Added the ability to login with username or email
GitHub link: https://github.com/uidaho/squireproject/pull/68

Added follow project functionality
- Follow a project
- Unfollow a project
- Display follower count for project

GitHub link: https://github.com/uidaho/squireproject/pull/111

Fixed issues on project list page
- Titles and descriptions overflowing
- Pictures not scaling correctly
- Project thumbnails not of equal size

GitHub link: https://github.com/uidaho/squireproject/pull/117

Added tests for Project comments
- Tests auth/non-auth users view
- Creating a comment
- Editing a comment
- Deleting a comment

GitHub link: https://github.com/uidaho/squireproject/pull/124

Added tests for Project following
- Tests auth/non-auth users view
- Following a project
- Users view after someone else follows the project
- Unfollowing a project

GitHub link: https://github.com/uidaho/squireproject/pull/124

Added 403 page (forbidden access) 
GitHub link: https://github.com/uidaho/squireproject/pull/119

Project Permissions to join
- Request to join (Partial) 
- Cancel request
- Accept request (Partial)
- Deny request (Partial)

GitHub link: https://github.com/uidaho/squireproject/tree/auth

**Comment by brandonjank** [comment]
everything above this post has been added. Need screenshot from your best work for the project,  and authentication controllers.

**Comment by brandonjank** [comment]
submitted, closing.
