### ISSUE TITLE
File editor editable usernames

### ISSUE THREAD

**Issue by brec9824** [uidaho/squireproject#132]
Usernames are currently editable in the file editor. This should be changed so users cant do this.

**Comment by brandonjank** [comment]
Not a bug, this will be an editable status field when the chat is integrated.

**Comment by brec9824** [comment]
If thats what it will be used for shouldnt it also display the users name somewhere. So others now who it is

**Comment by brandonjank** [comment]
it will, i just didnt remove it to remind me to do it later ;)

**Comment by brec9824** [comment]
Ok, then I will just close this
