### ISSUE TITLE
Delete File

### ISSUE THREAD

**Issue by rickbau5** [uidaho/squireproject#133]
Doesn't seem to be working on master branch?

**Comment by brandonjank** [comment]
It was working when committed and demonstrated in class Stopped working at 91d11cf50373a56222c984b288ae0d8c8d737f4f

**Comment by rickbau5** [comment]
I have the merge PR right before that checked out, still getting the same error. I found this bug because I was getting that error with Firebase as well when trying to access a file like you do in `EditorController@delete`, namely here:

``` php
$firebase = new \Firebase\FirebaseLib(env('FIREBASE_URL'), env('FIREBASE_TOKEN'));
$firebase->delete($firebase_path);
```

when I found that wasn't working for me, I tested the delete and it was also not working. The two env variables are null.
![image](https://cloud.githubusercontent.com/assets/11299264/14836859/252a2034-0bc8-11e6-9c39-9bb56f1a30df.png)

**Comment by brandonjank** [comment]
was the file actually created in firebase? I just tested creating a file and removing it with current master and it worked fine.

**Comment by brandonjank** [comment]
give me the file path that you cant delete and ill check

**Comment by rickbau5** [comment]
`Spaces/NewFile.java` is the file path. I'm trying from here: https://boss2849.squireproject.com/editor/edit/Spaces/NewFile.java

**Comment by brandonjank** [comment]
I'd have to go through your branch, but right now on master deletion works fine

**Comment by rickbau5** [comment]
Putting a `dd` before it makes the connection shows that the environment variables the are being passed to firebase are null
I figure it's those variables.
![image](https://cloud.githubusercontent.com/assets/11299264/14837128/a109b69a-0bca-11e6-9e83-0c8d1a7e4609.png)

**Comment by brandonjank** [comment]
does your .env contain:

```
FIREBASE_URL=https://radiant-torch-8044.firebaseio.com/
FIREBASE_TOKEN=
```

**Comment by rickbau5** [comment]
Ah nope that's it.

**Comment by brandonjank** [comment]
any files created without that in your .env will bork. I recommend pruning your database and the migrating/seeding again

**Comment by rickbau5** [comment]
aight cool. thanks for the help!
