### ISSUE TITLE
Login with email display error

### ISSUE THREAD

**Issue by brec9824** [uidaho/squireproject#138]
If you try to login with an email and type in your password incorrectly. The pages formatting breaks down. 
![error](https://cloud.githubusercontent.com/assets/16866862/14873428/24fe916a-0cab-11e6-9868-26b21007b99f.PNG)

**Comment by brandonjank** [comment]
fixed with 580bf27. I must note that the input should be taken by the view and the controller should try the username then email as a key. Really hackish :octopus:  Too late to rewrite though ;)
