### ISSUE TITLE
Identify a modest list of easy-to-obtain metrics for your system.

### ISSUE THREAD

**Issue by brandonjank** [uidaho/squireproject#144]
Include at least: #directories, #files, #classes, #methods, largest class/method, source lines of code, static disk requirements for binary distribution, run-time memory requirements.

**Comment by brec9824** [comment]
Got some metrics using phpstorm plugin metricsreloaded. Ran this on the directories app, bootstrap, config, database, public, resources, storage, and tests all together. I will add these images to the HW8 folder on cloud9.
![metrics_1](https://cloud.githubusercontent.com/assets/16866862/15101281/ca2c59cc-1540-11e6-81bb-0221a28496da.PNG)
![metrics_files](https://cloud.githubusercontent.com/assets/16866862/15101280/ca2c0512-1540-11e6-83c1-566a883c1808.PNG)
![metrics_loc](https://cloud.githubusercontent.com/assets/16866862/15101282/ca2efcf4-1540-11e6-89c0-2e6ef5dd70f1.PNG)

**Comment by rickbau5** [comment]
Nice :+1:

**Comment by brandonjank** [comment]
had to change these out for new ones, it was counting a bunch of dependencies, not just our work. integrated into MRS, closing.
