### ISSUE TITLE
squireproject.com cleanup

### ISSUE THREAD

**Issue by brec9824** [uidaho/squireproject#148]
Currently squireproject.com has some temp projects with random data. It would be nice to get the database nuked and remigrated. So we could fill it with some nice looking fake projects for display tomorrow. 

@backburn maybe tonight or tomorrow morning clear it all after the last merge and tomorrow before class we can all fill in some fake projects to make it look nice.

**Comment by brandonjank** [comment]
I've emptied the DB and created a project called Unit Testing

**Comment by brandonjank** [comment]
@brec9824 want to create a few?

**Comment by brec9824** [comment]
@backburn I am currently working on something but tomorrow morning I will create a bunch of projects.

**Comment by brec9824** [comment]
@backburn can we get one more db nuke because I just merged profiles branch
