### ISSUE TITLE
Files

### ISSUE THREAD

**Issue by brec9824** [uidaho/squireproject#151]
I dont know if this is something new that someone just got added or what but every time I create a new file it is filled with a whole bunch of code.

**Comment by brandonjank** [comment]
its because of the db wipes, re-using project_ids file_ids

**Comment by brandonjank** [comment]
All of our projects are using the same firebase database ;) I could wipe the firebase database, but I think that would cause more problems.

**Comment by brec9824** [comment]
Ok just wasnt sure what I was seeing.
