### ISSUE TITLE
Setting Up MySQL Database

### ISSUE THREAD

**Issue by rickbau5** [uidaho/squireproject#26]
Could we get some instructions for everyone on how to set up their MySQL database? I just got mine set up, but i sort of used a work around. Just dumped @brec9824's, changed the db name in it and uploaded it to phpmyadmin. Dunno if this is how everyone should be doing it, but it worked for me.

Thoughts @backburn?

**Comment by brandonjank** [comment]
That method works, but should not be done that way. The database is setup by the artisan command that runs the database migration code. See https://laravel.com/docs/5.2/migrations 

If your code needs new tables in the database then you will need to write a migration. Migrations are in squireproject/database/migration/

TLDR: run the command "php artisan migrate" while in the squireproject folder.
