### ISSUE TITLE
Add more documentation to the Wiki

### ISSUE THREAD

**Issue by brandonjank** [uidaho/squireproject#27]
We need more documentation for the wiki. I've placed what was in c9 in the wiki. Click 'New Page' at the top to add a new page, or edit existing pages for clarity.

**Comment by rickbau5** [comment]
I did a bit of editing to use markdown. I'll be sure to use this as I find more things to add. Make sure to push this wiki so people look at it and use it!

**Comment by brandonjank** [comment]
I markeddown whatever was left, closing.
