### ISSUE TITLE
Review all class diagrams.

### ISSUE THREAD

**Issue by brandonjank** [uidaho/squireproject#32]
Review all class diagrams, consider all aggregations to see if they should instead be a user-defined association. If they have an association name, get the diamond off them; it is either/or. Association names should not be whole sentences or long phrases; those go in the diagram dictionary.

**Comment by brandonjank** [comment]
@uidaho/lambda make sure you do this tonight for your class diagrams in c9

**Comment by ghost** [comment]
I have reviewed all the class diagrams and made the appropriate corrections.

**Comment by rickbau5** [comment]
awesome thanks!

**Comment by drop-table-lol** [comment]
This is set as completed, but many of our class diagrams havn't been updated. They have the same issues Dr. J had with them last sprint. It may be that the class diagrams were updated, but the UML diagrams themselves were not

**Comment by rickbau5** [comment]
@drop-table-lol alright, i'll reopen this and assign you
