### ISSUE TITLE
Add "Created by X, reviewed by X." to the footer of each diagram.

### ISSUE THREAD

**Issue by brandonjank** [uidaho/squireproject#34]
Review and/or add reviewer information to sequence diagrams if it is not already present.

**Comment by brandonjank** [comment]
@uidaho/lambda make sure you do this tonight for your diagrams in c9

**Comment by ghost** [comment]
I have created a Review folder in the diagrams folder of master requirements. This contains diagrams needing reviewed and a subfolder of claim which has all the diagrams without "Created by:". I reviewed most of the diagrams but I need someone to review mine.

**Comment by ghost** [comment]
A fix folder has been added for diagrams needing corrections. I added comments to the diagrams that need a large amount of corrections.

**Comment by ghost** [comment]
Format has been updated to:
Created by: Name (ID)
Reviewed by: Name (ID)
Audit DATE by: Name (ID)

This changes has been made to most diagrams.

**Comment by rickbau5** [comment]
Nice thanks :+1: i'll get on this before class tomorro

**Comment by rickbau5** [comment]
closing this
