### ISSUE TITLE
Make Profile Page: Projects

### ISSUE THREAD

**Issue by ghost** [uidaho/squireproject#37]
Create a profile page with a list of projects a user is a part of.

**Comment by rickbau5** [comment]
I've created a projects table and project model for us, once i get it pushed to the main branch you'll be able to grab the list of projects a user is a part of

**Comment by ghost** [comment]
Thanks, I will take a look at that.

**Comment by brandonjank** [comment]
functionality added in https://github.com/uidaho/squireproject/commit/5a7e4c90dcfca2dd9198a4d43da7313dda171da6
