### ISSUE TITLE
Permissions Issue with Artisan

### ISSUE THREAD

**Issue by rickbau5** [uidaho/squireproject#38]
Trying to make a new artisan command:
`php artisan make:commmand PopulateProjectsTable`
Fails with a permissions error for `storage/logs/laravel.log`. 
~~Trying to change the permission with chmod fails with `chmod: changing permissions of ‘storage/logs/laravel.log’: Operation not permitted`
And I can't sudo. @backburn help?~~
EDIT:
Actually I think it's a deeper issue than permissions, and i realize now that it is already rwx (oops). Might need a server restart? See here:

http://stackoverflow.com/questions/30362459/laravel-5-permission-denied-when-writing-in-log-file/30362460#30362460

**Comment by brandonjank** [comment]
I have set the php5-fpm server to run under each of your users individually. Files should be created using your user/group instead of www-data now.

I chowned all files in your storage directory to you. You should be able to run the command now.

**Comment by rickbau5** [comment]
Nice thanks it's working :+1:
