### ISSUE TITLE
Write documentation for setting up IDE and floobits

### ISSUE THREAD

**Issue by brandonjank** [uidaho/squireproject#41]
https://github.com/uidaho/squireproject/wiki/Setup-IDE

**Comment by rickbau5** [comment]
Wanna add the section about setting up the remote workspace upload/download stuff? Like we did at the meeting on wednesday?

**Comment by brandonjank** [comment]
Aye

**Comment by brandonjank** [comment]
Re-writing for using c9 as editor.

**Comment by brandonjank** [comment]
Dcoumentation can be found on the wiki at https://github.com/uidaho/squireproject/wiki/Setup-IDE
