### ISSUE TITLE
Create implementation section for hw6 deliverable.

### ISSUE THREAD

**Issue by brandonjank** [uidaho/squireproject#43]
Regarding the implementation, the document should not include all source files, but rather, project organization (directories, summaries of files' contents) and JavaDoc or equivalent reference information.

**Comment by brec9824** [comment]
Ok I got an overview completed of our directories. Let me know if you think I should add something. I will probably add a subsection about authentication. Also the team working on settings/profile if you get a prototype implemented then make sure to add a subsection about it. Lastly attaching a PDF of the overview so everyone can take a quick look.
[Individual.pdf](https://github.com/uidaho/squireproject/files/211877/Individual.pdf)

**Comment by rickbau5** [comment]
I guess I don't really get what should be done for this... Should I write up about the project ideas stuff? Or more in detail on like `database` directory or something?

**Comment by brec9824** [comment]
I believe it will be a little right up of each sub system we complete explaining which files are used and what they do.

**Comment by rickbau5** [comment]
Hmm alright, i'll do a quick write up of the project stuff I've done.

**Comment by brec9824** [comment]
I believe this section is done so I am closing.

**Comment by rickbau5** [comment]
:+1:
