### ISSUE TITLE
Create outline for sprint report due 4/11

### ISSUE THREAD

**Issue by brandonjank** [uidaho/squireproject#44]
In your sprint report, demo use cases that are done and non-usecase progress that has been made.

Make a list of things we accomplished on github and the prototypes on the web.

**Comment by brec9824** [comment]
I created an outline for this weeks sprint report. @bolt1003 and I will be presenting this weeks sprint report (Correct me if I am wrong but I believe Ben said he was going to present with me). Let me know if I should add anything to the list of what to talk about. Especially the settings/profile team I am not sure what progress you guys have made. Adding everyone so everyone takes a look also take a look at issue #43 it has to deal with our group submission @backburn @drspaceman0 @mora5651 @rickbau5

### Sprint Overview:

#### Use cases:

##### Authentication:
- Sign up
- Login
- Logout
- Forgotten Password

##### Project Ideas:
- Browse Project Ideas (In-progress boss2849)
- View Project Idea (In-progress boss2849)

##### Settings/Profile:
- ???

#### GitHub:
- Working under our own branches
- Backlog for project is in the issues section
- Wiki – includes how setup up of server, ide, phpMyAdmin, Git commands, and our workspace setup
- Integrated slack for team communication
- Setup travis.ci for project testing

**Comment by ghost** [comment]
**Sprint Overview**
**_Settings / Profile**_
- View A User's Profile (In-progress mora5651,mars2681,bolt1003)
- Modify Profile Info (In-progress mora5651,mars2681,bolt1003)
- Modify Profile Privacy (In-progress mora5651,mars2681,bolt1003)
