### ISSUE TITLE
Slack GitHub Integration

### ISSUE THREAD

**Issue by rickbau5** [uidaho/squireproject#45]
The Slack integration isn't working for some reason. I think you need to grant access for it to the organization, as per this link https://get.slack.help/hc/en-us/articles/204270098-Adding-a-new-GitHub-organization-to-Slack

Then it can be configured from here: https://uidaho.slack.com/apps/manage/A0F7YS2SX-github

**Comment by brandonjank** [comment]
Integration has not be requested by slack. I do not have the owner permission on slack to force it.
![2016-04-10 10_17_14-uidaho - oauth applications](https://cloud.githubusercontent.com/assets/784730/14411743/acb1e0e8-ff05-11e5-9966-08c403bdfce3.png)

**Comment by rickbau5** [comment]
K, check again should be there now

**Comment by brandonjank** [comment]
Access granted. Closing.

**Comment by rickbau5** [comment]
Still getting this? Reopening but I'll look into this
![screen shot 2016-04-10 at 6 26 19 pm](https://cloud.githubusercontent.com/assets/11299264/14414572/c82c810e-ff49-11e5-9702-0caad54c92ff.png)

**Comment by brandonjank** [comment]
looks like it wants admin perms on github. I made you an admin on github. try now

**Comment by rickbau5** [comment]
Ok that should do it. Closed closed :+1:
