### ISSUE TITLE
Add ability to upload a photo for project

### ISSUE THREAD

**Issue by brandonjank** [uidaho/squireproject#48]
@uidaho/lambda 
Right now the picture is directly referenced and manually placed in the images/projects folder. When a person edits their project page it should allow them to upload a new image, or provide a url to one.

**Comment by rickbau5** [comment]
Yup, I avoided tackling this in my initial implementation. I don't mind the link to image idea, but it's always a bit nicer when a site has hosting. However, we don't yet have the file system structure set up for projects, which is ideally where that would go (thereby making it editable).

**Comment by rickbau5** [comment]
Added a temporary version until the project file structure is set up completely. See here: https://github.com/uidaho/squireproject/commit/7f87f1a6cd0f8b2850e1fda5b3a051357294e1c6
