### ISSUE TITLE
Resize diagrams in Master Requirements Specification

### ISSUE THREAD

**Issue by brec9824** [uidaho/squireproject#51]
Sum of the diagrams in the Master Requirements Specification are pixelated and need to have their widths adjusted before submission tonight.

**Comment by ghost** [comment]
All the diagrams in the diagrams folder as of 3:30 have been resized.
If you move a file into the diagrams folder please resize the diagram by placing:

scale max 700 width

in the uml.

**Comment by ghost** [comment]
I looked over all the diagrams and all have a max width of 700.
