### ISSUE TITLE
Test All the Things!

### ISSUE THREAD

**Issue by rickbau5** [uidaho/squireproject#55]
With the first major pull request, it became obvious we need these. I'll be working on this tonight.

Moved test outlines to [wiki](https://github.com/uidaho/squireproject/wiki/Unit-Tests)

**Comment by brandonjank** [comment]
![unit-test-all-the-things](https://cloud.githubusercontent.com/assets/784730/14448403/5446e3c2-001d-11e6-85df-d20fec1a5f31.jpg)

Fixed that for you.

**Comment by rickbau5** [comment]
hahahaha perfect. I should print this out and put it on my wall

**Comment by rickbau5** [comment]
first couple unit tests are done! see them [here](https://github.com/uidaho/squireproject/compare/master...tests).

Done:
- Create Project
- Login 
- Register
- User view (logged in vs. logged out)

**Comment by rickbau5** [comment]
added checklist of tests to write to original comment. Feel free to add, or do tests that are not implemented yet.

**Comment by rickbau5** [comment]
Moved the checklist to the wiki: https://github.com/uidaho/squireproject/wiki/Unit-Tests

**Comment by rickbau5** [comment]
@uidaho/lambda keep this in mind, i'm going to leave it open and `ongoing`.

**Comment by brandonjank** [comment]
Closing this, if specific things need testing open a new issue for each one.
