### ISSUE TITLE
Integrate Editor

### ISSUE THREAD

**Issue by rickbau5** [uidaho/squireproject#59]
Get a dummy page set up for the ace editor within what we have now

**Comment by rickbau5** [comment]
@backburn interested?

**Comment by brandonjank** [comment]
ill take it. will be the "editor" controller

**Comment by rickbau5** [comment]
:+1:

**Comment by brandonjank** [comment]
got a basic and ugly version working

must be logged in:

https://jank6275.squireproject.com/editor/1

**Comment by rickbau5** [comment]
I get this on a for some of the files, and when i try to create a new one :( 
![screen shot 2016-04-14 at 1 41 51 pm](https://cloud.githubusercontent.com/assets/11299264/14542973/b1534e4a-0246-11e6-9243-8ffbd14c25b5.png)

**Comment by brandonjank** [comment]
What URL did you use for the create page?

**Comment by rickbau5** [comment]
the create button, so this link: https://jank6275.squireproject.com/editor/create/1

**Comment by brandonjank** [comment]
try now, i had to replace . with - in filenames for firebase to work

**Comment by rickbau5** [comment]
:+1: working now

**Comment by brandonjank** [comment]
plenty to do before i do a pull request, but if you see any more edge cases let me know

**Comment by rickbau5** [comment]
@backburn can we close this?
