### ISSUE TITLE
Integrate "Chat Client"

### ISSUE THREAD

**Issue by rickbau5** [uidaho/squireproject#60]
~~Integrate the dummy chat client into the sQuire ecosystem as it is now. Just want to see it as a page.~~ The real thing now!

**Comment by rickbau5** [comment]
Referring to [this guy](https://www.squireproject.com/chateditor.html)

**Comment by brandonjank** [comment]
Ill take it

**Comment by rickbau5** [comment]
:+1:

**Comment by rickbau5** [comment]
Adding this to the [upcoming milestone](https://github.com/uidaho/squireproject/milestones/Foundation%20&%20Tests), as it is one of the base features

**Comment by brandonjank** [comment]
almost complete, not committing until after the weekend

**Comment by brandonjank** [comment]
Addressed in pull request #146, closing.
