### ISSUE TITLE
Favicon!

### ISSUE THREAD

**Issue by rickbau5** [uidaho/squireproject#66]
It's time! We need a [favicon](https://en.wikipedia.org/wiki/Favicon)!

**Comment by brandonjank** [comment]
@uidaho/lambda who feels like an artist?

**Comment by rickbau5** [comment]
![image](https://cloud.githubusercontent.com/assets/11299264/14503837/a668f4ca-0166-11e6-8f10-903c2901f120.png)
:penguin: 
This is why we need someone artistic to do it

**Comment by eric-marsh** [comment]
@rickbau5 In pull #70, this issue has been adressed. Please review

**Comment by brandonjank** [comment]
Issue successfully resolved with pull #70, closing.
