### ISSUE TITLE
Login with username or email

### ISSUE THREAD

**Issue by brec9824** [uidaho/squireproject#67]
Allow for login with email are username.

**Comment by rickbau5** [comment]
[maybe?](https://laravel.com/docs/5.1/authentication#authenticating-users)

**Comment by brec9824** [comment]
I figured out a fix and will submit it later. Its a little hacky but works.

**Comment by brec9824** [comment]
Wow, just saw your link. I should have checked the documentation. :anguished:

**Comment by brec9824** [comment]
Issue fixed resolved with pull #68, closing.

**Comment by rickbau5** [comment]
Nice :+1: also just fyi if you write fixes/resolves/completes #issue-number in a commit / pull request it will auto close that issue when it gets merged to master :)
