### ISSUE TITLE
Error requesting password reset

### ISSUE THREAD

**Issue by rickbau5** [uidaho/squireproject#7]
Getting an error requesting a password reset:

`at Swift_Transport_AbstractSmtpTransport->_assertResponseCode('530 5.7.1 Authentication required ', array('250')) in AbstractSmtpTransport.php`

**Comment by brandonjank** [comment]
It should be set to MAIL_Driver=mail if you want e-mails to be sent. No need to change other settings with the simple php mail driver.

**Comment by brec9824** [comment]
Brandon are you sure the server is setup to send emails or if their is something else that needs to be set? Because the error goes away but I am not receiving the email.

**Comment by brec9824** [comment]
I will just add this if anyone doesn't want it to send emails but want it to log:

In .env file set MAIL_Driver=log. The log is found in config/logs/laravel.log at the very bottom it will include the email with the reset link.

**Comment by brandonjank** [comment]
try the sendmail driver if mail is not working. Also check the spam folder.

**Comment by brandonjank** [comment]
I verified that sendmail is installed and php is configured to use it. Try MAIL_Driver=sendmail in your .env

**Comment by brec9824** [comment]
Yep that fixed it now it works.

**Comment by brandonjank** [comment]
I have updated the .env.example to fix this. Closing.
