### ISSUE TITLE
Add link from project page to editor/files

### ISSUE THREAD

**Issue by brandonjank** [uidaho/squireproject#72]
The project page should like to the project file listing. The listing will be found at /editor/projectname, and specific file can be edited using /editor/projectname/filename

Keep in mind, we must use the project's name (no spaces allowed) not the id # in routes. You may need to validate projectname fields when creating projects.

@brec9824 @rickbau5

**Comment by rickbau5** [comment]
will do, still working on changes to the `project` route, but will use titles instead of id's

**Comment by rickbau5** [comment]
This was resolved with #92 and #91
