### ISSUE TITLE
Project, file and username naming convention

### ISSUE THREAD

**Issue by brandonjank** [uidaho/squireproject#73]
I recommend we use the github way. Regex: [A-Za-z0-9_.-]+

We can error on any other character or replace all other characters, like spaces, with '-'.

@uidaho/lambda

**Comment by brandonjank** [comment]
Example validation for creating a file:

```
        $this->validate($request, [
            'filename' => 'required|unique:files|max:255|regex:/([A-Za-z0-9_.-]+)/',
            'description' => 'required',
        ]);
```

**Comment by rickbau5** [comment]
Yeah I think that sounds good. I tend to use `[]` and `()` in file names, not for coding purposes but in other cases, this wouldn't accept those. and replacing them with `-` seems wonky.

**Comment by brandonjank** [comment]
if you put a { or ( in a github repo name it would change them to -'s

**Comment by brandonjank** [comment]
prolly best to just error and have the user fix it so we don't do something unexpected.

**Comment by rickbau5** [comment]
Projects have been [updated](https://github.com/uidaho/squireproject/commit/ff24383e4cbc9e4592c0028a04e1aa564e0681fd#diff-33d60f9cc69d473cb04584baf77d7c4cR27). Note that for projects I **disallow** dashes, as it would conflict with trying convert dashes into spaces and fail look ups.

**Comment by brec9824** [comment]
Just wanted to add naming convention should also make sure the user has one letter or number. So something like this regex:/(?=.*[a-zA-Z0-9])([A-Za-z0-9_ .]+)/ so we dont get allot of names like this: _______

**Comment by brandonjank** [comment]
closing.
