### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by rickbau5** [uidaho/squireproject#76]
So now my stuff looks like this...?
![image](https://cloud.githubusercontent.com/assets/11299264/14578714/6062f2ca-0344-11e6-85aa-7a1041e5d204.png)

**Comment by brec9824** [comment]
Looks like @backburn got bootstrap css setup in master and the pages just need formatting. @backburn am I correct.

**Comment by brandonjank** [comment]
Correct. I'll have things looking better tonight

**Comment by brandonjank** [comment]
Check out layoutit.com and bootswatch.com

**Comment by brec9824** [comment]
@backburn do you want me to make issues for each page? So anyone can jump on a page and set it up.

**Comment by brandonjank** [comment]
sure, though ill have most of them done tonight. However, @rickbau5  just forked master and dropped a bunch of commits, gonna need to hand merge everything now :(

**Comment by brec9824** [comment]
Ok I will just wait on it and if I notice any are not done tomorrow I will make issues on them then.

**Comment by brandonjank** [comment]
looks like we got everything fixed, gonna start working on the other views
if you want to help tonight call me on skype, b.jank

**Comment by brandonjank** [comment]
Use this as your guide: https://bootswatch.com/yeti/

**Comment by rickbau5** [comment]
resolved
