### ISSUE TITLE
Don't Work on Master?

### ISSUE THREAD

**Issue by rickbau5** [uidaho/squireproject#80]
@backburn can you work on your own branch please. It's hard for me to find a place to start with all your changes half baked. Thanks!

**Comment by brandonjank** [comment]
Had to rewrite a lot. I'm done with refactoring and implementation for the sprint and just working on unit tests now.

**Comment by rickbau5** [comment]
Ok, it's just hard for the rest of us to work on it at the same time. Its just easier if everything happens in branches and gets merged.

**Comment by brandonjank** [comment]
definitely a part of the great debate ;)

**Comment by rickbau5** [comment]
Actually when it comes to collaboration using Git and GitHub, there's really no debate haha. It's the way it's done!
