### ISSUE TITLE
Routes with spaces in them

### ISSUE THREAD

**Issue by brec9824** [uidaho/squireproject#81]
I have noticed routes that contain spaces end up getting switched with %20 and can cause future routes to fail. Only fix I found was checking every time if a route contains a space and replacing it. I noticed @rickbau5 was doing this for project titles but curious if anyone's got a better idea then having to constantly check for spaces.

**Comment by rickbau5** [comment]
yeah i wasn't sure how to do this, but i just threw that fix in cause it worked. Should see if there's a better way for sure

**Comment by brandonjank** [comment]
already fixed that in the current master

**Comment by brandonjank** [comment]
FYI true routes should never have a space or -.  Laravel technically does not support - in a pure route. But we are injecting a - in variables to a route more-or-less

See:
https://laravel.com/docs/5.2/routing#route-parameters

> Note: Route parameters cannot contain the - character. Use an underscore (_) instead.

**Comment by brandonjank** [comment]
This should now be resolved with pull request #136.
