### ISSUE TITLE
Master projects go straight to file manager

### ISSUE THREAD

**Issue by brec9824** [uidaho/squireproject#82]
The master branch when you click on a project it goes straight to the projects file manager. Skipping the project's view page.

**Comment by rickbau5** [comment]
works on my branch, @backburn may have recently broke it in his commits.

**Comment by rickbau5** [comment]
proof: https://boss2849.squireproject.com/project

**Comment by brec9824** [comment]
Yeah its working in my older branch too. Trying to find whats going on in my issue79 branch that is up to date.

**Comment by brec9824** [comment]
Figured it out the project page was removed. So I am adding it back so I have a place for comments to go.

**Comment by brec9824** [comment]
Uh, now issue #81 is causing problems.

**Comment by brandonjank** [comment]
https://boss2849.squireproject.com/project looks like the old broken layout to me, are you sure you have the right branch? There is a hybrid template for including the project files anywhere. The project view was just amended to show the files. There is still a editor pages with just files and no project info.

**Comment by rickbau5** [comment]
Yeah it wasn't up to date, it was an old state of master. Aka the stuff you were actively working on so i think that's where the problems were coming from

**Comment by brandonjank** [comment]
that was from before my changes ;) after the js/css change to bootstrap

**Comment by rickbau5** [comment]
Ah ok gotcha
