### ISSUE TITLE
Master deleting a project causes 404

### ISSUE THREAD

**Issue by brec9824** [uidaho/squireproject#83]
In master if click delete you get a 404 error and the project isnt deleted.

**Comment by rickbau5** [comment]
fixed in a branch i'm working on

**Comment by brandonjank** [comment]
path is wrong, should be /project/delete/projectname  according to routes.php needs to be updated.

**Comment by brandonjank** [comment]
fixed with branch issue83

**Comment by brec9824** [comment]
Fixed with merge #90
