### ISSUE TITLE
Project titles are spilling over

### ISSUE THREAD

**Issue by brec9824** [uidaho/squireproject#84]
Titles for projects are spilling out of their boxes if they are long. This is on the project finder page and the file manager page.
![error](https://cloud.githubusercontent.com/assets/16866862/14589516/0ade7e40-0499-11e6-9eb6-2014b5fed9fc.PNG)

**Comment by rickbau5** [comment]
dat pic though

**Comment by brec9824** [comment]
Lol, biology project pic. To lazy to go get other pictures.

**Comment by brandonjank** [comment]
names should be limited at creation ;) 
otherwise, application.css needs to be modified to wrap that div.

**Comment by rickbau5** [comment]
They currently are limited, but it's pretty grandiose. What's a good length to limit it to?

**Comment by rickbau5** [comment]
This is a duplicate with #64

**Comment by rickbau5** [comment]
I'm going to close this one, as the other one includes description and is still relevant
