### ISSUE TITLE
Request Username Retrieval

### ISSUE THREAD

**Issue by rickbau5** [uidaho/squireproject#9]
Add method for users to request retrieval of their usernames.

**Comment by brandonjank** [comment]
we could also allow them to use their e-mail or username to login.

**Comment by brec9824** [comment]
Just found out since the authentication is done be middleware it will need to be coded from scratch for the most part to get username or email for login. Kind of dumb.

**Comment by rickbau5** [comment]
That won't be too crazy difficult right? You could have the user enter their email, and then in the controller that receives that request just do 

``` php
$user = DB::table('users')->where('email', '=', Request::input('name-of-element'))
```

to retrieve the user then just fire off an email to them, or return an error if no user with that email exists!

**Comment by brec9824** [comment]
From what I looked at currently the authentication middleware functions are in a file composer pulls in so it cant be edited. I thought about editing some of the data then redirecting back to the middleware but I get errors. So I think to get this and login with a email or username will require doing the authentication from scratch. Which wont be to bad but will be annoying.

**Comment by rickbau5** [comment]
oh oh, i see I misunderstood your previous comment, I was thinking of sending the username in an email to user for forgotten username

**Comment by rickbau5** [comment]
@brec9824 if it's too much work, feel free to mark it as won't do and just ignore it. For fringe functionality like this, I think it's ok to do

**Comment by brec9824** [comment]
@rickbau5 I think if we need any changes to how the current built in authentication works will require doing it from scratch. Laravel's built in authentication seems to be limited and barely editable. If the team is fine with how it is now we might as well just leave it and get other systems working.

**Comment by rickbau5** [comment]
i'm good with login only being by username if adding email is going to be _too_ tough :+1:

**Comment by brandonjank** [comment]
Cleaning up issues, closing unimplemented feature request.
