### ISSUE TITLE
Import/Export/Rename in Editor Doesn't Work

### ISSUE THREAD

**Issue by rickbau5** [uidaho/squireproject#95]
Get 404's for Import/Export (not implemented?) and an error for Rename - `Method App\Http\Controllers\EditorController::renameView() does not exist`.

**Comment by rickbau5** [comment]
@backburn this is still an issue. Is this functionality going to be implemented or should these buttons be removed?

**Comment by rickbau5** [comment]
Working on this since it's an easy extension from compilation stuff

**Comment by brandonjank** [comment]
Rename just needs to change the value in the projects table. The firebase uses file_ids and does not care. Ill whip that up now and leave import/export to you. :+1:

**Comment by brandonjank** [comment]
rename implimented

**Comment by rickbau5** [comment]
@backburn i've done export and import as well as part of mine, that cool?

**Comment by brandonjank** [comment]
sounds great

**Comment by rickbau5** [comment]
added importing/exporting with #150. Closing
