### ISSUE TITLE
User Permissions for Projects

### ISSUE THREAD

**Issue by rickbau5** [uidaho/squireproject#99]
This is open to discussion, as I forget the details. Are we doing user gating for a project, as in the author must approve collaborators? 

If this is the case, other issues to follow will be 
- Inviting User to Project
- Accepting Invite to Project
- Declining Invite to Project
- Request to join a project

@uidaho/lambda thoughts?

**Comment by brec9824** [comment]
This is how I thought it was going to work.

**Comment by brec9824** [comment]
Request to join done

**Comment by rickbau5** [comment]
The user should be able to go to a section where they can view all their requests and projects they are part of. Probably include that with profiles (#24)

**Comment by brec9824** [comment]
Yeah definitely. Good thing it only takes one line of code to see all of them.

**Comment by brandonjank** [comment]
Completed by @brec9824 and merged, closing.
